import Airtable from 'airtable';
import Head from 'next/head';
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function March22() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Turner Fenton Secondary School</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full px-4">
            <div className="text-center mx-auto mt-[100px] lg:mb-20 max-w-[510px]">
               <h2
                  className="
                  font-bold
                  text-3xl
                  pt-5
                  sm:text-4xl
                  md:text-[40px]
                  text-black
                  
                  "
                  >
                 Classes Overview
               </h2>

            </div>
         </div>
      <main className={styles.classes}>
      <div className="p-5 bg-gray-300 rounded-lg border border-gray-100">
<time className="text-lg font-semibold text-gray-900">Week 5</time>
<ol className="mt-3 divide-y divider-gray-200">
<li>
<a href="https://user1agam.notion.site/Course-Content-3aff36bd65ee4890b038862bc528edc0" className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">Analyze Round 2 Specifics</div>
</div>
</a>
</li>
<li>
<a href="https://docs.google.com/document/d/1pbH7aCREN-nQ3_r60S7cncQ2HYlaTQBUZmQ1aVizH5M/edit" className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">Patient Data Case Study</div>
</div>
</a>
</li>
<li>
<a href="https://forms.gle/WhgokGKrKttEoUaeA" className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">Practice Exam</div>
</div>
</a>
</li>
</ol>
</div>

<br/>

<div className="p-5 bg-gray-300 rounded-lg border border-gray-100">
<time className="text-lg font-semibold text-gray-900">Week 4</time>
<ol className="mt-3 divide-y divider-gray-200">
<li>
<a href="https://drive.google.com/file/d/1cLmUIjrjz7Zd4KKEgEAPC9SitbBe8YhY/view?usp=sharing" className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">Applying Analytical Tools</div>
</div>
</a>
</li>
<li>
<a href="https://docs.google.com/forms/d/1qZrxkEw8vOUgkVwMXRJlPRsQ7BXEI1aASd02jh7ny_E/edit" className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">Practice Exam</div>
</div>
</a>
</li>
<li>
<a href="https://www.mbaknol.com/management-case-studies/case-study-success-story-of-pfizer-inc/" className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">Pfizer Case Study</div>
</div>
</a>
</li>
</ol>
</div>

<br/>

      <div className="p-5 bg-gray-300 rounded-lg border border-gray-100">
<time className="text-lg font-semibold text-gray-900">Week 3</time>
<ol className="mt-3 divide-y divider-gray-200">
<li>
<a href="https://docs.google.com/presentation/d/1brJHYE_uKCaAX6b8nQY7bJQkM3zejXpbahbQfymO_Rg/edit?usp=sharing" className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">DECA Tools Lesson</div>
</div>
</a>
</li>
<li>
<a href="https://docs.google.com/forms/d/1qZrxkEw8vOUgkVwMXRJlPRsQ7BXEI1aASd02jh7ny_E/edit" className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">Practice Exam</div>
</div>
</a>
</li>
<li>
<a className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">Analyzing Real-Life Case Studies</div>
</div>
</a>
</li>
</ol>
</div>

<br/>

      <div className="p-5 bg-gray-300 rounded-lg border border-gray-100">
<time className="text-lg font-semibold text-gray-900">Week 2</time>
<ol className="mt-3 divide-y divider-gray-200">
<li>
<a href="https://www.canva.com/design/DAE36NeSykc/share/preview?token=ruRuYfjFvspO7kT5f7MLMQ&role=EDITOR&utm_content=DAE36NeSykc&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton" className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">What is the new debate oriented case study?</div>
</div>
</a>
</li>
<li>
<a href="https://docs.google.com/document/d/1mGIUw8xjRaWfZfZd44Rzlc2bmNfdcvSUj6d2lW2tH-M/edit?usp=sharing" className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">Debate Case Study Practice</div>
</div>
</a>
</li>
<li>
<a href="https://docs.google.com/forms/d/1Ur-blIkrWUI7ZLPDEw01BJfarnCIHKsh5GqDIyDc6lg/edit" className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">Practice Exam</div>
</div>
</a>
</li>
</ol>
</div>

<br/>


<div className="p-5 bg-gray-300 rounded-lg border border-gray-100">
<time className="text-lg font-semibold text-gray-900">Week 1</time>
<ol className="mt-3 divide-y divider-gray-200">
<li>
<a className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">Briefing JOT Regionals & News with Cases</div>
</div>
</a>
</li>
<li>
<a href="https://drive.google.com/drive/u/0/folders/1LfDnzZQy6n6fvj6REylazdb9RIvOyPpG" className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">Reviewing the Case</div>
</div>
</a>
</li>
<li>
<a href="https://jeopardylabs.com/play/jot-health-sciences-jeopardy" className="block items-center p-3 sm:flex hover:bg-gray-200">
<div className="text-gray-900">
<div className="text-base font-normal">JOT Health Sci Jeopardy</div>
</div>
</a>
</li>
</ol>
</div>

 
<br/><br/>
        
      </main>
    </div>
  )
}

