import Airtable from 'airtable';
import Head from 'next/head';
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function March22() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Turner Fenton Secondary School</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <section className="pt-20 lg:pt-[120px] pb-5 lg:pb-5">
   <div className="container">
      <div className="flex flex-wrap justify-center -mx-4">
         <div className="w-full px-4">
            <div className="text-center mx-auto mb-[60px] lg:mb-20 max-w-[510px]">
               <h2
                  className="
                  font-bold
                  text-3xl
                  sm:text-4xl
                  md:text-[40px]
                  text-black
                  mb-4
                  "
                  >
                 March 22 Overview
               </h2>
              {/* <div className="display-flex">
               <button className="text-black p-3 "><b><Link href="/clubs=name">Name</Link></b></button>
               <button className="text-black p-3"> <Link href="/clubs=status">Status</Link></button>
          </div> */}
            </div>
         </div>
      </div>
   </div>
</section>
        
        <div className={styles.grid}>
    
<div className="max-w-sm rounded-lg border m-3 shadow-md bg-gray-300 border-gray-300">
  <div className="p-5">
      <a href="#"
      style={{
        display: 'flex',
      }}
      >
          <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-black">Agam&#39;s Overview</h5>
<div>

</div>
      </a>

      <p className="mb-3 font-normal text-gray-700"><i>words</i></p>
      <a href="#" className="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white rounded-lg bg-blue-900 hover:bg-blue-800 focus:ring-blue-800">
            Explore
            <svg className="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd"></path></svg>
        </a>
  </div>
</div>

<div className="max-w-sm rounded-lg border m-3 shadow-md bg-gray-300 border-gray-300">
  <div className="p-5">
      <a href="#"
      style={{
        display: 'flex',
      }}
      >
          <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-black">words</h5>
<div>

</div>
      </a>

      <p className="mb-3 font-normal text-gray-700"><i>words</i></p>
      <a href="#" className="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white rounded-lg bg-blue-900 hover:bg-blue-800 focus:ring-blue-800">
            Explore
            <svg className="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd"></path></svg>
        </a>
  </div>
</div>

<div className="max-w-sm rounded-lg border m-3 shadow-md bg-gray-300 border-gray-300">
  <div className="p-5">
      <a href="#"
      style={{
        display: 'flex',
      }}
      >
          <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-black">words</h5>
<div>

</div>
      </a>

      <p className="mb-3 font-normal text-gray-700"><i>words</i></p>
      <a href="#" className="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white rounded-lg bg-blue-900 hover:bg-blue-800 focus:ring-blue-800">
            Explore
            <svg className="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd"></path></svg>
        </a>
  </div>
</div>

<div className="max-w-sm rounded-lg border m-3 shadow-md bg-gray-300 border-gray-300">
  <div className="p-5">
      <a href="#"
      style={{
        display: 'flex',
      }}
      >
          <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-black">words</h5>
<div>

</div>
      </a>

      <p className="mb-3 font-normal text-gray-700"><i>words</i></p>
      <a href="#" className="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white rounded-lg bg-blue-900 hover:bg-blue-800 focus:ring-blue-800">
            Explore
            <svg className="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd"></path></svg>
        </a>
  </div>
</div>

    </div>

        
      </main>
    </div>
  )
}

